### ISSUE TITLE
Better to avoid `unwrap`

### ISSUE THREAD

**Issue by pronvis** [Anchor-Protocol/anchor-bAsset-contracts#50]
https://github.com/Anchor-Protocol/anchor-bAsset-contracts/blob/16ce81910c0253d82cec029e08165a70d148a605/contracts/anchor_basset_reward/src/global.rs#L91

It is better to avoid `unwrap` in a production code. 

Just replace it with `?`. Maybe worth to fix it in moving to cosmwasm 0.14 version

---

Same here: https://github.com/Anchor-Protocol/anchor-bAsset-contracts/blob/16ce81910c0253d82cec029e08165a70d148a605/contracts/anchor_basset_reward/src/user.rs#L42 and
https://github.com/Anchor-Protocol/anchor-bAsset-contracts/blob/16ce81910c0253d82cec029e08165a70d148a605/contracts/anchor_basset_reward/src/user.rs#L156
https://github.com/Anchor-Protocol/anchor-bAsset-contracts/blob/16ce81910c0253d82cec029e08165a70d148a605/contracts/anchor_basset_reward/src/user.rs#L157

**Comment by MSNTCS** [comment]
@invis87 thank you for the issue, we will reflect on the new version of code.

**Comment by MSNTCS** [comment]
This issue is addressed in this PR #49. @pronvis thanks for the report.
